### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Hackerv706** [Sitiaro/Phisher-X#1]
im getting this message when i open it in a new tab.
i have it running and it still is saying it.

"Run The Repl
To see output."

**Comment by Sitiaro** [comment]
> im getting this message when i open it in a new tab.
> i have it running and it still is saying it.
> 
> "Run The Repl
> To see output."

Did you follow all the steps correctly? Also, did you try reloading the page/restarting the repl? Try those. If neither of them works then please upload a ss.
