### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by drumplayer123456** [Sitiaro/Phisher-X#2]
On first install after I follow the steps it gives me 
`./phisherx.sh: 9: [[: not found`
`./phisherx.sh: 12: [[: not found`
`trap: SIGINT; bad trap`
`trap: SIGTERM; bad trap`
`./phisherx.sh: 86: Syntax error: "(" unexpected (expecting "fi")`

**Comment by Sitiaro** [comment]
What are you using? It's working perfectly for me.

![termux_1](https://user-images.githubusercontent.com/46511306/135560610-eacc2431-71d2-4b1e-8815-404f3659953b.JPG)
![termux_2](https://user-images.githubusercontent.com/46511306/135560627-782004bf-9433-4475-88fa-dec534273f64.JPG)
.

**Comment by Sitiaro** [comment]
> On first install after I follow the steps it gives me `./phisherx.sh: 9: [[: not found` `./phisherx.sh: 12: [[: not found` `trap: SIGINT; bad trap` `trap: SIGTERM; bad trap` `./phisherx.sh: 86: Syntax error: "(" unexpected (expecting "fi")`

Try using bash phisherx.sh instead of ./phisherx.sh

**Comment by drumplayer123456** [comment]
It worked, but do you know when a gmail link is going to be added?

**Comment by Sitiaro** [comment]
> It worked, but do you know when a gmail link is going to be added?

I'll add it ASAP.
